name: hydroevents

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - plotly
  - openpyxl
  - jupyter
  - notebook
  - ipykernel