#!/usr/bin/env bash
# Create (or update) the hydroevents conda environment and install the
# package in editable mode.
#
# By default this uses a conda/miniconda already available on PATH.
# Pass -p <dir> to instead bootstrap a private Miniconda distribution
# into <dir> (useful on machines with no global conda install) and
# build the environment there.
set -euo pipefail

ENV_NAME="hydroevents"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$REPO_DIR/environment.yml"

MINICONDA_URL_LINUX="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
MINICONDA_URL_MACOS="https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-p <install_dir>] [-h]

  -p <install_dir>   Bootstrap a private Miniconda distribution into
                      <install_dir> instead of using a global conda
                      install, then build the '${ENV_NAME}' env there.
  -h                  Show this help message.

With no options, an existing 'conda' on PATH is used.
EOF
}

install_dir=""
while getopts "p:h" opt; do
  case "$opt" in
    p) install_dir="$OPTARG" ;;
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done

if [ -n "$install_dir" ]; then
  install_dir="$(mkdir -p "$install_dir" && cd "$install_dir" && pwd)"
  echo "==> Using private conda distribution at: $install_dir"

  if [ -x "$install_dir/bin/conda" ]; then
    echo "==> Existing installation found, reusing it."
  else
    case "$(uname -s)" in
      Linux)  installer_url="$MINICONDA_URL_LINUX" ;;
      Darwin) installer_url="$MINICONDA_URL_MACOS" ;;
      *) echo "error: unsupported OS '$(uname -s)' for automatic Miniconda install" >&2; exit 1 ;;
    esac

    tmp_installer="$(mktemp --suffix=.sh)"
    trap 'rm -f "$tmp_installer"' EXIT

    echo "==> Downloading Miniconda installer..."
    curl -fsSL "$installer_url" -o "$tmp_installer"

    echo "==> Installing Miniconda into $install_dir..."
    bash "$tmp_installer" -b -u -p "$install_dir"
  fi

  conda_base="$install_dir"
else
  if ! command -v conda >/dev/null 2>&1; then
    echo "error: no 'conda' found on PATH." >&2
    echo "Either install conda/Miniconda globally first, or run:" >&2
    echo "  $(basename "${BASH_SOURCE[0]}") -p <install_dir>" >&2
    exit 1
  fi
  conda_base="$(conda info --base)"
  echo "==> Using conda install at: $conda_base"
fi

# shellcheck disable=SC1091
source "$conda_base/etc/profile.d/conda.sh"

if conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
  echo "==> Environment '$ENV_NAME' already exists, updating from environment.yml..."
  conda env update -n "$ENV_NAME" -f "$ENV_FILE" --prune
else
  echo "==> Creating environment '$ENV_NAME' from environment.yml..."
  conda env create -n "$ENV_NAME" -f "$ENV_FILE"
fi

conda activate "$ENV_NAME"

echo "==> Installing hydroevents in editable mode..."
python -m pip install -e "$REPO_DIR"

# Safety net: remove a stray installer left in the repo by an older run
if [ -f "$REPO_DIR/miniconda.sh" ]; then
  rm -f "$REPO_DIR/miniconda.sh"
fi

activate_file="$REPO_DIR/activate_env.sh"
cat > "$activate_file" <<EOF
# Auto-generated by setup_conda_env.sh. Do not edit by hand; rerun
# setup_conda_env.sh to regenerate.
#
# Usage:
#   source activate_env.sh
source "$conda_base/etc/profile.d/conda.sh"
conda activate "$ENV_NAME"
EOF

echo ""
echo "==> Done."
echo "==> To use this environment in a new shell, run:"
echo "      source \"$activate_file\""
